### ISSUE TITLE
Dawg nodeid issue

### ISSUE THREAD

**Issue by rohithkodali** [aosingh/lexpy#1]
HI,

  There is an issue with your Dawg data-structure. The maximum nodeId that it can reach is 2. I tried to print the nodeid and val while inserting and here is the output i got

id and val at current is  1 
id and val at current is  2 a
id and val at current is  2 n
id and val at current is  2 p
id and val at current is  2 e
id and val at current is  2 p
id and val at current is  2 l
id and val at current is  2 e
id and val at current is  2 b
id and val at current is  2 a
id and val at current is  2 n
id and val at current is  2 a
id and val at current is  2 n
id and val at current is  2 a
id and val at current is  2 t
id and val at current is  2 c
id and val at current is  2 a
id and val at current is  2 n
id and val at current is  2 a
id and val at current is  2 n
id and val at current is  2 a

it is not creating a child id after first child from root

**Comment by aosingh** [comment]
@rohithkodali : Ok, I will have a look at it and let you know.

**Comment by oscardssmith** [comment]
Can confirm the issue. It happens because Dawg.id doesn't get updated as intended.

**Comment by aosingh** [comment]
This issue should be resolved in lexpy version 0.9.6.

**Comment by aosingh** [comment]
Closing this issue
