### ISSUE TITLE
adding word information

### ISSUE THREAD

**Issue by rohithkodali** [aosingh/lexpy#2]
As an update is there any way that we can add some information about a word for exmaple wordcount in a text or POS tag or something and result both the searched word and its value

example input:    arc:1200
                            art:1450
                            bar:2300

example output:  dawg.search_with_prefix("a")
                        [arc:1200,art:1450]

**Comment by aosingh** [comment]
I am currently working on finalizing requirements for the next version of lexpy and I will address this issue in that version. 

It could take some time to draft the requirements and the changes in the API. I will post them here for a critical review. 

Thank you for your patience.

**Comment by aosingh** [comment]
In lexpy version 0.9.7, you can now associate a count with each word. Please check the documentation for more details.
