### ISSUE TITLE
search_with_suffix function

### ISSUE THREAD

**Issue by slee7268** [aosingh/lexpy#4]
Do you think there's a way to implement a search_with_suffix function that looks for words in the DAWG that contain some suffix? Also is there a way to search the DAWG for words that contain a substring? For instance, if I wanted words that contained the substring "ST," the function would return "first," "star," and "sophisticated" Thanks!

**Comment by aosingh** [comment]
Hi @slee7268 

For substring like usecase, will the search() method be useful ? I tested something like below. 
Let me know if this works:

```python
from lexpy.dawg import DAWG
dawg = DAWG()
words = ["start", "first", "star", "thirst", "saturday", "sophisticate"]
dawg.add_all(words)
dawg.search("*st*") # wildcard search
['star', 'start', 'first', 'sophisticate', 'thirst'] # output
```

**Comment by aosingh** [comment]
Also, for search_with_suffix like use-case, the wild-card pattern should work. Do let me know if you feel this is not what you want. 

```python
from lexpy.dawg import DAWG
dawg = DAWG()
words = ["foobar", "crowbar", "metalbar", "coolbar", "bars"]
dawg.add_all(words)
dawg.search("*bar") # wild card char at the beginning. 
['coolbar', 'crowbar', 'foobar', 'metalbar']
```

**Comment by slee7268** [comment]
Thanks that makes sense! Lexpy is awesome!!

**Comment by aosingh** [comment]
Glad it helped :)
