### ISSUE TITLE
In operator returning true when should be false

### ISSUE THREAD

**Issue by TomsonBoylett** [aosingh/lexpy#6]
The following code prints true.
```
trie = Trie()
trie.add_all(['ash', 'ashley'])
print('mash lolley' in trie)
```
Just needs a small change to return false when the letter is not in node.children
https://github.com/aosingh/lexpy/blob/8535dcb1ec692dee588d4eff31f8d24cc31d1d95/lexpy/_base/automata.py#L39

**Comment by TomsonBoylett** [comment]
#7

**Comment by aosingh** [comment]
Thank you @TomsonBoylett for creating a pull request. The changes have been successfully merged into the master branch. 
I will close this issue for now.
